language: node_js
node_js:
  - "stable"
dist: xenial
os: linux
script:
  - npm install
  - npm run build
  - npm run build:docs
deploy:
  provider: pages
  skip_cleanup: true
  strategy: git
  token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
before_deploy:
  - touch .nojekyll
  - touch docs/.nojekyll